version: "3.3"

networks:
  firefly:
    name: firefly

services:
  firefly:
    container_name: firefly
    hostname: firefly
    image: fireflyiii/core:latest
    restart: unless-stopped
    networks:
      - firefly
    ports:
      - 8082:8080
    depends_on:
      firefly-mariadb:
        condition: service_healthy
    environment:
    ###
      - SITE_OWNER=finance@jelletimmerman.com
      - APP_KEY=k4yPfFNzkiweiVQEFBzXbYSEHydu8RK3   # generate with: head /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9' | head -c 32 && echo
      - STATIC_CRON_TOKEN=b9c5c95363e271b8f3bb2bdf383024ac0466af96a2ba4200ca27dea24c0c8ab5   # generate with: openssl rand -hex 32
      - TZ=Europe/Amsterdam
      - DEFAULT_LANGUAGE=en_US
      - DEFAULT_LOCALE=equal
      - TRUSTED_PROXIES=*
      - APP_ENV=local
      - APP_DEBUG=false
      - LOG_CHANNEL=stdout
      - APP_LOG_LEVEL=info
      - AUDIT_LOG_LEVEL=emergency
      ### db settings
      - DB_CONNECTION=mysql
      - DB_HOST=firefly-mariadb
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=firefly
      ### cookie settings
      - COOKIE_PATH="/"
      - COOKIE_DOMAIN=
      - COOKIE_SECURE=false
      - COOKIE_SAMESITE=lax
      ### email settings
      - MAIL_MAILER=imap
      - MAIL_HOST=box.jelletimmerman.com
      - MAIL_PORT=993
      - MAIL_FROM=finance@jelletimmerman.com
      - MAIL_USERNAME=finance@jelletimmerman.com
      - MAIL_PASSWORD=Gi7wBEHiICFfiTVi
      - MAIL_ENCRYPTION=ssl
      - SEND_ERROR_MESSAGE=true
      - SEND_REPORT_JOURNALS=true
      ### misc
      - ENABLE_EXTERNAL_MAP=false
      - ENABLE_EXTERNAL_RATES=false
      - MAP_DEFAULT_LAT=51.983333
      - MAP_DEFAULT_LONG=5.916667
      - MAP_DEFAULT_ZOOM=6
    volumes:
      - ./upload:/var/www/html/storage/upload


  firefly-importer:
    container_name: firefly-importer
    image: fireflyiii/data-importer:latest
    restart: no  # when set to automatic import, container goes into a loop, set it to "no" to avoid
    networks:
      - firefly
    ports:
      - 8083:8080  # after enabling automatic folder import (see below) this port mapping can be removed
    environment:
      - TZ=Europe/Amsterdam
      - WEB_SERVER=true   # set to true to make it import from folder automatically, after you have created and download json config
      - FIREFLY_III_URL=http://firefly:8080
      - VANITY_URL=https://firefly.jelletimmerman.info
      - FIREFLY_III_ACCESS_TOKEN=ABC
      - NORDIGEN_SANDBOX=false
      - NORDIGEN_ID=ABC
      - NORDIGEN_KEY=ABC
      - AUTO_IMPORT_SECRET=ABC   #  generate with: openssl rand -hex 32
      - IGNORE_DUPLICATE_ERRORS=false
      - CAN_POST_AUTOIMPORT=true
      - CAN_POST_FILES=true
      - IMPORT_DIR_ALLOWLIST=/import
      - VERIFY_TLS_SECURITY=true
      - EXPECT_SECURE_URL=false
      - APP_NAME=DataImporter
      - APP_ENV=local
      - APP_DEBUG=false
      - LOG_CHANNEL=stdout
      - LOG_LEVEL=info
      - TRUSTED_PROXIES=*
      - ENABLE_MAIL_REPORT=true
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
      - MAIL_DESTINATION=username@gmail.com
      - MAIL_FROM=username@gmail.com
      - MAIL_FROM_ADDRESS=username@gmail.com
      - MAIL_USERNAME=username@gmail.com
      - MAIL_PASSWORD=password
      - MAIL_ENCRYPTION=ssl
    volumes:
      - ./import:/import

  firefly-mariadb:
    container_name: firefly-mariadb
    image: mariadb:11.1.2
    restart: unless-stopped
    networks:
      - firefly
    environment:
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=firefly
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=firefly
      - MYSQL_DATABASE=firefly
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin --user=$${MYSQL_USER} --password=$${MYSQL_PASSWORD} --host=localhost ping"]
